<?php

namespace ContainerG58VYfq;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsersApiControllercreateUSersService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..znCIbn.App\Controller\UsersApiController::createUSers()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..znCIbn.App\\Controller\\UsersApiController::createUSers()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'validator' => ['privates', 'debug.validator', 'getDebug_ValidatorService', false],
            'serializer' => ['privates', 'debug.serializer', 'getDebug_SerializerService', false],
        ], [
            'validator' => '?',
            'serializer' => '?',
        ]))->withContext('App\\Controller\\UsersApiController::createUSers()', $container);
    }
}
